
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class City : _City
	{
		public City()
		{
		
		}

        public virtual bool LoadWithCountry()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_City_LoadWithCountry]");
        }

        public virtual bool LoadByName(string cityName, string countryName)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CityName", SqlDbType.VarChar), cityName);
            parameters.Add(new SqlParameter("@CountryName", SqlDbType.VarChar), countryName);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_City_LoadByName]", parameters);
        }

        public virtual bool LoadDetailInfo(int cityID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CityID", SqlDbType.Int), cityID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_City_LoadDetailInfo]", parameters);
        }
	}
}
