
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using  VikkiSoft_BLL.DAL;

namespace  VikkiSoft_BLL
{
	public class Site : _Site
	{
		public Site()
		{
		
		}

        public virtual bool LoadWithSiteTypeName()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadWithSiteTypeName]");
        }

        public virtual bool LoadBySiteTypeID(int siteTypeID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SiteTypeID", SqlDbType.Int), siteTypeID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadBySiteTypeID]", parameters);
        }
	}
}
