
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using  VikkiSoft_BLL.DAL;

namespace  VikkiSoft_BLL
{
	public class Site : _Site
	{
		public Site()
		{
		
		}

        public virtual bool LoadWithSiteTypeName()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadWithSiteTypeName]");
        }
	}
}
