
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _City : SqlClientEntity
	{
		public _City()
		{
			this.QuerySource = "City";
			this.MappingName = "City";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllCity]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int CityID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.CityID, CityID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadCityByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter CityID
			{
				get
				{
					return new SqlParameter("@CityID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name_uk
			{
				get
				{
					return new SqlParameter("@Name_uk", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Name_en
			{
				get
				{
					return new SqlParameter("@Name_en", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Name_ru
			{
				get
				{
					return new SqlParameter("@Name_ru", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter CountryID
			{
				get
				{
					return new SqlParameter("@CountryID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Content_uk
			{
				get
				{
					return new SqlParameter("@Content_uk", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Content_en
			{
				get
				{
					return new SqlParameter("@Content_en", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Content_ru
			{
				get
				{
					return new SqlParameter("@Content_ru", SqlDbType.VarChar, 2147483647);
				}
			}
			
			public static SqlParameter Keywords_uk
			{
				get
				{
					return new SqlParameter("@Keywords_uk", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Keywords_en
			{
				get
				{
					return new SqlParameter("@Keywords_en", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Keywords_ru
			{
				get
				{
					return new SqlParameter("@Keywords_ru", SqlDbType.VarChar, 250);
				}
			}
			
			public static SqlParameter Active
			{
				get
				{
					return new SqlParameter("@Active", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter Description_uk
			{
				get
				{
					return new SqlParameter("@Description_uk", SqlDbType.VarChar, 200);
				}
			}
			
			public static SqlParameter Description_en
			{
				get
				{
					return new SqlParameter("@Description_en", SqlDbType.VarChar, 200);
				}
			}
			
			public static SqlParameter Description_ru
			{
				get
				{
					return new SqlParameter("@Description_ru", SqlDbType.VarChar, 200);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string CityID = "CityID";
            public const string Name_uk = "Name_uk";
            public const string Name_en = "Name_en";
            public const string Name_ru = "Name_ru";
            public const string CountryID = "CountryID";
            public const string Content_uk = "Content_uk";
            public const string Content_en = "Content_en";
            public const string Content_ru = "Content_ru";
            public const string Keywords_uk = "Keywords_uk";
            public const string Keywords_en = "Keywords_en";
            public const string Keywords_ru = "Keywords_ru";
            public const string Active = "Active";
            public const string Description_uk = "Description_uk";
            public const string Description_en = "Description_en";
            public const string Description_ru = "Description_ru";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CityID] = _City.PropertyNames.CityID;
					ht[Name_uk] = _City.PropertyNames.Name_uk;
					ht[Name_en] = _City.PropertyNames.Name_en;
					ht[Name_ru] = _City.PropertyNames.Name_ru;
					ht[CountryID] = _City.PropertyNames.CountryID;
					ht[Content_uk] = _City.PropertyNames.Content_uk;
					ht[Content_en] = _City.PropertyNames.Content_en;
					ht[Content_ru] = _City.PropertyNames.Content_ru;
					ht[Keywords_uk] = _City.PropertyNames.Keywords_uk;
					ht[Keywords_en] = _City.PropertyNames.Keywords_en;
					ht[Keywords_ru] = _City.PropertyNames.Keywords_ru;
					ht[Active] = _City.PropertyNames.Active;
					ht[Description_uk] = _City.PropertyNames.Description_uk;
					ht[Description_en] = _City.PropertyNames.Description_en;
					ht[Description_ru] = _City.PropertyNames.Description_ru;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string CityID = "CityID";
            public const string Name_uk = "Name_uk";
            public const string Name_en = "Name_en";
            public const string Name_ru = "Name_ru";
            public const string CountryID = "CountryID";
            public const string Content_uk = "Content_uk";
            public const string Content_en = "Content_en";
            public const string Content_ru = "Content_ru";
            public const string Keywords_uk = "Keywords_uk";
            public const string Keywords_en = "Keywords_en";
            public const string Keywords_ru = "Keywords_ru";
            public const string Active = "Active";
            public const string Description_uk = "Description_uk";
            public const string Description_en = "Description_en";
            public const string Description_ru = "Description_ru";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[CityID] = _City.ColumnNames.CityID;
					ht[Name_uk] = _City.ColumnNames.Name_uk;
					ht[Name_en] = _City.ColumnNames.Name_en;
					ht[Name_ru] = _City.ColumnNames.Name_ru;
					ht[CountryID] = _City.ColumnNames.CountryID;
					ht[Content_uk] = _City.ColumnNames.Content_uk;
					ht[Content_en] = _City.ColumnNames.Content_en;
					ht[Content_ru] = _City.ColumnNames.Content_ru;
					ht[Keywords_uk] = _City.ColumnNames.Keywords_uk;
					ht[Keywords_en] = _City.ColumnNames.Keywords_en;
					ht[Keywords_ru] = _City.ColumnNames.Keywords_ru;
					ht[Active] = _City.ColumnNames.Active;
					ht[Description_uk] = _City.ColumnNames.Description_uk;
					ht[Description_en] = _City.ColumnNames.Description_en;
					ht[Description_ru] = _City.ColumnNames.Description_ru;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string CityID = "s_CityID";
            public const string Name_uk = "s_Name_uk";
            public const string Name_en = "s_Name_en";
            public const string Name_ru = "s_Name_ru";
            public const string CountryID = "s_CountryID";
            public const string Content_uk = "s_Content_uk";
            public const string Content_en = "s_Content_en";
            public const string Content_ru = "s_Content_ru";
            public const string Keywords_uk = "s_Keywords_uk";
            public const string Keywords_en = "s_Keywords_en";
            public const string Keywords_ru = "s_Keywords_ru";
            public const string Active = "s_Active";
            public const string Description_uk = "s_Description_uk";
            public const string Description_en = "s_Description_en";
            public const string Description_ru = "s_Description_ru";

		}
		#endregion		
		
		#region Properties
	
		public virtual int CityID
	    {
			get
	        {
				return base.Getint(ColumnNames.CityID);
			}
			set
	        {
				base.Setint(ColumnNames.CityID, value);
			}
		}

		public virtual string Name_uk
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_uk);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_uk, value);
			}
		}

		public virtual string Name_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_en, value);
			}
		}

		public virtual string Name_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Name_ru, value);
			}
		}

		public virtual int CountryID
	    {
			get
	        {
				return base.Getint(ColumnNames.CountryID);
			}
			set
	        {
				base.Setint(ColumnNames.CountryID, value);
			}
		}

		public virtual string Content_uk
	    {
			get
	        {
				return base.Getstring(ColumnNames.Content_uk);
			}
			set
	        {
				base.Setstring(ColumnNames.Content_uk, value);
			}
		}

		public virtual string Content_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Content_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Content_en, value);
			}
		}

		public virtual string Content_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Content_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Content_ru, value);
			}
		}

		public virtual string Keywords_uk
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords_uk);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords_uk, value);
			}
		}

		public virtual string Keywords_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords_en, value);
			}
		}

		public virtual string Keywords_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords_ru, value);
			}
		}

		public virtual bool Active
	    {
			get
	        {
				return base.Getbool(ColumnNames.Active);
			}
			set
	        {
				base.Setbool(ColumnNames.Active, value);
			}
		}

		public virtual string Description_uk
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description_uk);
			}
			set
	        {
				base.Setstring(ColumnNames.Description_uk, value);
			}
		}

		public virtual string Description_en
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description_en);
			}
			set
	        {
				base.Setstring(ColumnNames.Description_en, value);
			}
		}

		public virtual string Description_ru
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description_ru);
			}
			set
	        {
				base.Setstring(ColumnNames.Description_ru, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_CityID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CityID) ? string.Empty : base.GetintAsString(ColumnNames.CityID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CityID);
				else
					this.CityID = base.SetintAsString(ColumnNames.CityID, value);
			}
		}

		public virtual string s_Name_uk
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_uk) ? string.Empty : base.GetstringAsString(ColumnNames.Name_uk);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_uk);
				else
					this.Name_uk = base.SetstringAsString(ColumnNames.Name_uk, value);
			}
		}

		public virtual string s_Name_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_en) ? string.Empty : base.GetstringAsString(ColumnNames.Name_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_en);
				else
					this.Name_en = base.SetstringAsString(ColumnNames.Name_en, value);
			}
		}

		public virtual string s_Name_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Name_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name_ru);
				else
					this.Name_ru = base.SetstringAsString(ColumnNames.Name_ru, value);
			}
		}

		public virtual string s_CountryID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CountryID) ? string.Empty : base.GetintAsString(ColumnNames.CountryID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CountryID);
				else
					this.CountryID = base.SetintAsString(ColumnNames.CountryID, value);
			}
		}

		public virtual string s_Content_uk
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Content_uk) ? string.Empty : base.GetstringAsString(ColumnNames.Content_uk);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Content_uk);
				else
					this.Content_uk = base.SetstringAsString(ColumnNames.Content_uk, value);
			}
		}

		public virtual string s_Content_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Content_en) ? string.Empty : base.GetstringAsString(ColumnNames.Content_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Content_en);
				else
					this.Content_en = base.SetstringAsString(ColumnNames.Content_en, value);
			}
		}

		public virtual string s_Content_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Content_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Content_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Content_ru);
				else
					this.Content_ru = base.SetstringAsString(ColumnNames.Content_ru, value);
			}
		}

		public virtual string s_Keywords_uk
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords_uk) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords_uk);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords_uk);
				else
					this.Keywords_uk = base.SetstringAsString(ColumnNames.Keywords_uk, value);
			}
		}

		public virtual string s_Keywords_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords_en) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords_en);
				else
					this.Keywords_en = base.SetstringAsString(ColumnNames.Keywords_en, value);
			}
		}

		public virtual string s_Keywords_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords_ru);
				else
					this.Keywords_ru = base.SetstringAsString(ColumnNames.Keywords_ru, value);
			}
		}

		public virtual string s_Active
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Active) ? string.Empty : base.GetboolAsString(ColumnNames.Active);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Active);
				else
					this.Active = base.SetboolAsString(ColumnNames.Active, value);
			}
		}

		public virtual string s_Description_uk
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description_uk) ? string.Empty : base.GetstringAsString(ColumnNames.Description_uk);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description_uk);
				else
					this.Description_uk = base.SetstringAsString(ColumnNames.Description_uk, value);
			}
		}

		public virtual string s_Description_en
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description_en) ? string.Empty : base.GetstringAsString(ColumnNames.Description_en);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description_en);
				else
					this.Description_en = base.SetstringAsString(ColumnNames.Description_en, value);
			}
		}

		public virtual string s_Description_ru
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description_ru) ? string.Empty : base.GetstringAsString(ColumnNames.Description_ru);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description_ru);
				else
					this.Description_ru = base.SetstringAsString(ColumnNames.Description_ru, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CityID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CityID, Parameters.CityID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_uk
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_uk, Parameters.Name_uk);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name_ru, Parameters.Name_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CountryID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Content_uk
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Content_uk, Parameters.Content_uk);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Content_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Content_en, Parameters.Content_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Content_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Content_ru, Parameters.Content_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords_uk
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords_uk, Parameters.Keywords_uk);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords_en, Parameters.Keywords_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords_ru, Parameters.Keywords_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Active
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description_uk
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description_uk, Parameters.Description_uk);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description_en
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description_en, Parameters.Description_en);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description_ru
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description_ru, Parameters.Description_ru);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CityID
		    {
				get
		        {
					if(_CityID_W == null)
	        	    {
						_CityID_W = TearOff.CityID;
					}
					return _CityID_W;
				}
			}

			public WhereParameter Name_uk
		    {
				get
		        {
					if(_Name_uk_W == null)
	        	    {
						_Name_uk_W = TearOff.Name_uk;
					}
					return _Name_uk_W;
				}
			}

			public WhereParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public WhereParameter Name_ru
		    {
				get
		        {
					if(_Name_ru_W == null)
	        	    {
						_Name_ru_W = TearOff.Name_ru;
					}
					return _Name_ru_W;
				}
			}

			public WhereParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			public WhereParameter Content_uk
		    {
				get
		        {
					if(_Content_uk_W == null)
	        	    {
						_Content_uk_W = TearOff.Content_uk;
					}
					return _Content_uk_W;
				}
			}

			public WhereParameter Content_en
		    {
				get
		        {
					if(_Content_en_W == null)
	        	    {
						_Content_en_W = TearOff.Content_en;
					}
					return _Content_en_W;
				}
			}

			public WhereParameter Content_ru
		    {
				get
		        {
					if(_Content_ru_W == null)
	        	    {
						_Content_ru_W = TearOff.Content_ru;
					}
					return _Content_ru_W;
				}
			}

			public WhereParameter Keywords_uk
		    {
				get
		        {
					if(_Keywords_uk_W == null)
	        	    {
						_Keywords_uk_W = TearOff.Keywords_uk;
					}
					return _Keywords_uk_W;
				}
			}

			public WhereParameter Keywords_en
		    {
				get
		        {
					if(_Keywords_en_W == null)
	        	    {
						_Keywords_en_W = TearOff.Keywords_en;
					}
					return _Keywords_en_W;
				}
			}

			public WhereParameter Keywords_ru
		    {
				get
		        {
					if(_Keywords_ru_W == null)
	        	    {
						_Keywords_ru_W = TearOff.Keywords_ru;
					}
					return _Keywords_ru_W;
				}
			}

			public WhereParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public WhereParameter Description_uk
		    {
				get
		        {
					if(_Description_uk_W == null)
	        	    {
						_Description_uk_W = TearOff.Description_uk;
					}
					return _Description_uk_W;
				}
			}

			public WhereParameter Description_en
		    {
				get
		        {
					if(_Description_en_W == null)
	        	    {
						_Description_en_W = TearOff.Description_en;
					}
					return _Description_en_W;
				}
			}

			public WhereParameter Description_ru
		    {
				get
		        {
					if(_Description_ru_W == null)
	        	    {
						_Description_ru_W = TearOff.Description_ru;
					}
					return _Description_ru_W;
				}
			}

			private WhereParameter _CityID_W = null;
			private WhereParameter _Name_uk_W = null;
			private WhereParameter _Name_en_W = null;
			private WhereParameter _Name_ru_W = null;
			private WhereParameter _CountryID_W = null;
			private WhereParameter _Content_uk_W = null;
			private WhereParameter _Content_en_W = null;
			private WhereParameter _Content_ru_W = null;
			private WhereParameter _Keywords_uk_W = null;
			private WhereParameter _Keywords_en_W = null;
			private WhereParameter _Keywords_ru_W = null;
			private WhereParameter _Active_W = null;
			private WhereParameter _Description_uk_W = null;
			private WhereParameter _Description_en_W = null;
			private WhereParameter _Description_ru_W = null;

			public void WhereClauseReset()
			{
				_CityID_W = null;
				_Name_uk_W = null;
				_Name_en_W = null;
				_Name_ru_W = null;
				_CountryID_W = null;
				_Content_uk_W = null;
				_Content_en_W = null;
				_Content_ru_W = null;
				_Keywords_uk_W = null;
				_Keywords_en_W = null;
				_Keywords_ru_W = null;
				_Active_W = null;
				_Description_uk_W = null;
				_Description_en_W = null;
				_Description_ru_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CityID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CityID, Parameters.CityID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_uk
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_uk, Parameters.Name_uk);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_en, Parameters.Name_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name_ru, Parameters.Name_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CountryID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CountryID, Parameters.CountryID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Content_uk
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Content_uk, Parameters.Content_uk);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Content_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Content_en, Parameters.Content_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Content_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Content_ru, Parameters.Content_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords_uk
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords_uk, Parameters.Keywords_uk);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords_en, Parameters.Keywords_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords_ru, Parameters.Keywords_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Active
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description_uk
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description_uk, Parameters.Description_uk);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description_en
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description_en, Parameters.Description_en);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description_ru
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description_ru, Parameters.Description_ru);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CityID
		    {
				get
		        {
					if(_CityID_W == null)
	        	    {
						_CityID_W = TearOff.CityID;
					}
					return _CityID_W;
				}
			}

			public AggregateParameter Name_uk
		    {
				get
		        {
					if(_Name_uk_W == null)
	        	    {
						_Name_uk_W = TearOff.Name_uk;
					}
					return _Name_uk_W;
				}
			}

			public AggregateParameter Name_en
		    {
				get
		        {
					if(_Name_en_W == null)
	        	    {
						_Name_en_W = TearOff.Name_en;
					}
					return _Name_en_W;
				}
			}

			public AggregateParameter Name_ru
		    {
				get
		        {
					if(_Name_ru_W == null)
	        	    {
						_Name_ru_W = TearOff.Name_ru;
					}
					return _Name_ru_W;
				}
			}

			public AggregateParameter CountryID
		    {
				get
		        {
					if(_CountryID_W == null)
	        	    {
						_CountryID_W = TearOff.CountryID;
					}
					return _CountryID_W;
				}
			}

			public AggregateParameter Content_uk
		    {
				get
		        {
					if(_Content_uk_W == null)
	        	    {
						_Content_uk_W = TearOff.Content_uk;
					}
					return _Content_uk_W;
				}
			}

			public AggregateParameter Content_en
		    {
				get
		        {
					if(_Content_en_W == null)
	        	    {
						_Content_en_W = TearOff.Content_en;
					}
					return _Content_en_W;
				}
			}

			public AggregateParameter Content_ru
		    {
				get
		        {
					if(_Content_ru_W == null)
	        	    {
						_Content_ru_W = TearOff.Content_ru;
					}
					return _Content_ru_W;
				}
			}

			public AggregateParameter Keywords_uk
		    {
				get
		        {
					if(_Keywords_uk_W == null)
	        	    {
						_Keywords_uk_W = TearOff.Keywords_uk;
					}
					return _Keywords_uk_W;
				}
			}

			public AggregateParameter Keywords_en
		    {
				get
		        {
					if(_Keywords_en_W == null)
	        	    {
						_Keywords_en_W = TearOff.Keywords_en;
					}
					return _Keywords_en_W;
				}
			}

			public AggregateParameter Keywords_ru
		    {
				get
		        {
					if(_Keywords_ru_W == null)
	        	    {
						_Keywords_ru_W = TearOff.Keywords_ru;
					}
					return _Keywords_ru_W;
				}
			}

			public AggregateParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public AggregateParameter Description_uk
		    {
				get
		        {
					if(_Description_uk_W == null)
	        	    {
						_Description_uk_W = TearOff.Description_uk;
					}
					return _Description_uk_W;
				}
			}

			public AggregateParameter Description_en
		    {
				get
		        {
					if(_Description_en_W == null)
	        	    {
						_Description_en_W = TearOff.Description_en;
					}
					return _Description_en_W;
				}
			}

			public AggregateParameter Description_ru
		    {
				get
		        {
					if(_Description_ru_W == null)
	        	    {
						_Description_ru_W = TearOff.Description_ru;
					}
					return _Description_ru_W;
				}
			}

			private AggregateParameter _CityID_W = null;
			private AggregateParameter _Name_uk_W = null;
			private AggregateParameter _Name_en_W = null;
			private AggregateParameter _Name_ru_W = null;
			private AggregateParameter _CountryID_W = null;
			private AggregateParameter _Content_uk_W = null;
			private AggregateParameter _Content_en_W = null;
			private AggregateParameter _Content_ru_W = null;
			private AggregateParameter _Keywords_uk_W = null;
			private AggregateParameter _Keywords_en_W = null;
			private AggregateParameter _Keywords_ru_W = null;
			private AggregateParameter _Active_W = null;
			private AggregateParameter _Description_uk_W = null;
			private AggregateParameter _Description_en_W = null;
			private AggregateParameter _Description_ru_W = null;

			public void AggregateClauseReset()
			{
				_CityID_W = null;
				_Name_uk_W = null;
				_Name_en_W = null;
				_Name_ru_W = null;
				_CountryID_W = null;
				_Content_uk_W = null;
				_Content_en_W = null;
				_Content_ru_W = null;
				_Keywords_uk_W = null;
				_Keywords_en_W = null;
				_Keywords_ru_W = null;
				_Active_W = null;
				_Description_uk_W = null;
				_Description_en_W = null;
				_Description_ru_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertCity]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.CityID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateCity]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteCity]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.CityID);
			p.SourceColumn = ColumnNames.CityID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.CityID);
			p.SourceColumn = ColumnNames.CityID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_uk);
			p.SourceColumn = ColumnNames.Name_uk;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_en);
			p.SourceColumn = ColumnNames.Name_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name_ru);
			p.SourceColumn = ColumnNames.Name_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CountryID);
			p.SourceColumn = ColumnNames.CountryID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Content_uk);
			p.SourceColumn = ColumnNames.Content_uk;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Content_en);
			p.SourceColumn = ColumnNames.Content_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Content_ru);
			p.SourceColumn = ColumnNames.Content_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords_uk);
			p.SourceColumn = ColumnNames.Keywords_uk;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords_en);
			p.SourceColumn = ColumnNames.Keywords_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords_ru);
			p.SourceColumn = ColumnNames.Keywords_ru;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Active);
			p.SourceColumn = ColumnNames.Active;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description_uk);
			p.SourceColumn = ColumnNames.Description_uk;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description_en);
			p.SourceColumn = ColumnNames.Description_en;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description_ru);
			p.SourceColumn = ColumnNames.Description_ru;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
